# Dependabot configuration for AutoAgent
# This configuration implements a conservative update strategy to prevent breaking changes
# from disrupting the development workflow, especially for major version updates.
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    # Ignore major version updates for critical dependencies
    # These require manual migration and testing
    ignore:
      # TypeScript: Major versions often have breaking changes
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      # Node types: Should match Node.js version in use
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
      # ESLint: v9+ requires configuration format migration
      - dependency-name: "eslint"
        versions: ["9.x", "10.x"]
      # Testing framework: Major versions may break test suites
      - dependency-name: "vitest"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@vitest/*"
        update-types: ["version-update:semver-major"]
    # Group updates to reduce PR noise and make testing easier
    groups:
      # Group all minor and patch updates for easier testing
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
        # Exclude packages that need individual attention
        exclude-patterns:
          - "eslint*"
          - "@typescript-eslint/*"
          - "typescript"
          - "vitest*"
          - "@vitest/*"
      # ESLint ecosystem: Keep these in sync
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
        update-types:
          - "minor"
          - "patch"
      # Testing tools: Update together for compatibility
      testing:
        patterns:
          - "vitest"
          - "@vitest/*"
        update-types:
          - "minor"
          - "patch"
      # Type definitions: Generally safe to update together
      types:
        patterns:
          - "@types/*"
        update-types:
          - "minor"
          - "patch"
      # Build tools: Keep in sync
      build-tools:
        patterns:
          - "typescript"
          - "npm-run-all"
          - "dotenv"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"