name: Dependency Review

on:
  pull_request:
    paths:
      - 'package.json'

permissions:
  contents: read

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    - name: Generate lock file for dependency review
      run: |
        # Generate a temporary package-lock.json for dependency review
        # This is only for CI analysis, not committed to the repo
        npm install --package-lock-only
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: high
        allow-licenses: MIT, Apache-2.0, BSD-3-Clause, BSD-2-Clause, ISC
        comment-summary-in-pr: true
    
    - name: Check dependency size impact
      run: |
        # Install dependencies and check bundle size
        npm install
        npm run build
        
        # Get size of dist directory
        DIST_SIZE=$(du -sh dist | cut -f1)
        echo "Build size: $DIST_SIZE"
        
        # Check if package is under 15KB gzipped (as per requirements)
        TAR_SIZE=$(tar czf - dist | wc -c | awk '{print $1/1024 "KB"}')
        echo "Gzipped size: $TAR_SIZE"