name: Test and Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Test on Node ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.x]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Build project
      run: npm run build
    
    - name: Run tests with coverage
      run: npm run test:coverage
    
    - name: Upload coverage reports to Codecov
      if: matrix.node-version == '22.x'
      uses: codecov/codecov-action@v4
      with:
        directory: ./coverage
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  version-check:
    name: Check Version Change
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Check if version was updated
      run: |
        # Get the base branch version
        git fetch origin ${{ github.base_ref }}
        BASE_VERSION=$(git show origin/${{ github.base_ref }}:package.json | grep '"version"' | cut -d '"' -f 4)
        
        # Get the PR branch version
        PR_VERSION=$(grep '"version"' package.json | cut -d '"' -f 4)
        
        echo "Base version: $BASE_VERSION"
        echo "PR version: $PR_VERSION"
        
        if [ "$BASE_VERSION" = "$PR_VERSION" ]; then
          echo "::error::Version in package.json has not been updated. Please update the version number."
          exit 1
        fi
        
        # Verify version format (semantic versioning)
        if ! echo "$PR_VERSION" | grep -E '^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?(\+[a-zA-Z0-9.-]+)?$' > /dev/null; then
          echo "::error::Invalid version format. Please use semantic versioning (e.g., 1.2.3, 1.2.3-beta.1)"
          exit 1
        fi

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm audit
      run: npm audit --production
      continue-on-error: true
    
    - name: Check for known vulnerabilities
      run: |
        npm audit --json --production > audit-report.json || true
        if [ -s audit-report.json ]; then
          echo "Security vulnerabilities found. Please review:"
          cat audit-report.json | jq '.vulnerabilities | to_entries[] | select(.value.severity == "high" or .value.severity == "critical") | {package: .key, severity: .value.severity, via: .value.via[0].title}'
        fi